### ISSUE TITLE
Cannot reproduce the same metrics of uncompensated images

### ISSUE THREAD

**Issue by kopxiong** [BingyaoHuang/CompenNet-plusplus#2]
Hi Bingyao,
    I followed your detailed guide and could run the codes successfully, but one question is that the metrics of uncompensated images are **PSNR=6.4713, RMSE=0.8229, SSIM=0.0531** in my results, which are a lot different from the metrics you provided in the CompenNet++ paper (**PSNR=9.5973, RMSE=0.5765, SSIM=0.0767**). So are the trained models's metrics and the validation result images. Does this matter or have I missed anything important during the training phase? Any comments or suggestions are highly appreciated, thanks!

Best,
Andy Xiong

**Comment by BingyaoHuang** [comment]
Hi Andy,

Thank you for pointing out this. 

I've update the code in [e150ac2](https://github.com/BingyaoHuang/CompenNet-plusplus/commit/e150ac24aab4638d5a338c61e5d72d6b37931d35), it should reproduce the uncompensated metrics of the ICCV'19 paper. 

Note that in the ICCV'19 paper, we compared `cam/warpSL/test` images (i.e., **geometrically corrected**) with `test` images (projector input GT), because we thought the PSNR/RMSE/SSIM are more meaningful when the pixels were registered. But at this moment, I think maybe it's better to report uncompensated metrics of both geometrically corrected (i.e., `cam/warpSL/test` when `iccv19_paper_uncompensated` flag on) and geometrically uncorrected (i.e., `cam/raw/test` when `iccv19_paper_uncompensated` flag off). 

Please let me know if the updated code works.

**Comment by kopxiong** [comment]
Hi Bingyao,

Thank you for your detailed comment! While after I used your latest code and set the _iccv19_paper_uncompensated_ flag on, I got the following results (**PSNR=11.7926, RMSE=0.4503, SSIM=0.4678**), which are still not close to the metrics in your paper. 

Another problem also confused me a lot. After training, I also tried to get the model inference results using _cam/raw/test_ and _cam_surf_test_ as network inputs. In my results, the images are blurrer but the projection surface curves in the images are lighter (for example, when using curve image as the surface) compared to the proposed results in the supplementary material of the paper. 

Best,
Andy

**Comment by BingyaoHuang** [comment]
@kopxiong 

1. > I got the following results (PSNR=11.7926, RMSE=0.4503, SSIM=0.4678), which are still not close to the metrics in your paper.

Please try [b93ffd9](https://github.com/BingyaoHuang/CompenNet-plusplus/commit/b93ffd9342472ed0d9dbb3390135a50a8c5af9fa).  Correction to [my last comment](https://github.com/BingyaoHuang/CompenNet-plusplus/issues/2#issuecomment-657738614): In the ICCV'19 paper, we compared `cam/raw/test` images with `cam/desire/test`. Please let me know if the updated code works.

2. > In my results, the images are blurrer but the projection surface curves in the images are lighter (for example, when using curve image as the surface) compared to the proposed results in the supplementary material of the paper.

The results in the main paper Fig. 6 and supplementary material are **camera-captured compensation results**, to reproduce our results, you need to have exactly the same setup as ours (hardware, environment lighting, surfaces, poses, etc), and then project the compensation image x*, i.e., [`prj_cmp_test`](https://github.com/BingyaoHuang/CompenNet-plusplus/blob/master/src/python/main.py#L236) to the surface and capture it. Clearly it is impossible to replicate our setups, actually this is why we proposed the setup-independent evaluation benchmark (main paper sec **3.8. Dataset and evaluation protocol**) such that all methods can be compared on it without replicating our setup or actual projection.

**Comment by kopxiong** [comment]
Hi @BingyaoHuang 

1. Yes, now I can get the same PSNR/RMSE/SSIM results on uncompensated images when comparing _cam/raw/test_ with _cam/desire/test_, thanks! But on valid dataset, I got PSNR=19.4183, RMSE=0.1865, SSIM=0.6757 while the results in your papers were PSNR=21.1127, RMSE=0.1540, SSIM=0.7369. Do I need to change anything similar to the uncompensated metrics?

2. One small question is why the uncompensated images look much brighter than the compensation results of other methods and the GT both in Figure 6 and supplementary materials? Aren't they under the same global lighting and camera setting?

Best,
Andy

**Comment by BingyaoHuang** [comment]
@kopxiong 

1. > But on valid dataset, I got PSNR=19.4183, RMSE=0.1865, SSIM=0.6757 while the results in your papers were PSNR=21.1127, RMSE=0.1540, SSIM=0.7369. Do I need to change anything similar to the uncompensated metrics?

Are your results averaged over the 20 setups? If so, could you post the results of each setup?

2. > why the uncompensated images look much brighter than the compensation results of other methods and the GT both in Figure 6 and supplementary materials?

The camera-projector parameters are coadjusted such that the brightest projected input image (plain white) slightly overexposes the camera captured image. Similarly, the darkest projected input image (plain black) slightly underexposes the camera captured image. **This allows the projector dynamic range to cover the full camera dynamic range.** Also, please refer to https://github.com/BingyaoHuang/CompenNet/issues/4.

**Comment by kopxiong** [comment]
Hi @BingyaoHuang 

Yes, my results are averaged over the whole 20 setups. A screenshot of the detailed results (due to some data transfer reasons, not able to provide the txt log) can be seen 
![CompenNet++_log](https://user-images.githubusercontent.com/12959006/87751189-0a98e880-c830-11ea-9a58-f3bcb40c6110.jpg)

Best,
Andy

**Comment by BingyaoHuang** [comment]
@kopxiong What is your PyTorch version?

**Comment by kopxiong** [comment]
@BingyaoHuang version 1.5.1

**Comment by BingyaoHuang** [comment]
@kopxiong Maybe it's version incompatibility. CompenNet++ was implemented using PyTorch 0.4.0 and it works well up to 1.1.0. Could you try it on PyTorch 1.1.0 and I'll address the 1.5.1 issue soon.

**Comment by kopxiong** [comment]
> 
> 
> @kopxiong Maybe it's version incompatibility. CompenNet++ was implemented using PyTorch 0.4.0 and it works well up to 1.1.0. Could you try it on PyTorch 1.1.0 and I'll address the 1.5.1 issue soon.

Yes, I think it is related to the pytorch version. I tried it on pytorch 1.1.0 and got the following PSNR/RMSE/SSIM results (**PSNR=21.1597, RMSE=0.1531, SSIM=0.7276**), which are very close to the results in your paper.

**Comment by BingyaoHuang** [comment]
@kopxiong Great! I've updated the code and now it should be compatible with PyTorch 1.2.0-1.5.1.

**Comment by kopxiong** [comment]
> 
> 
> @kopxiong Great! I've updated the code and now it should be compatible with PyTorch 1.2.0-1.5.1.

@BingyaoHuang Nice, thanks a lot!
